### ISSUE TITLE
No module named 'seggpt_engine'

### ISSUE THREAD

**Issue by alfheim1993** [autodistill/autodistill-seggpt#2]
Traceback (most recent call last):
  File "/home/smiv/Temp2018/ZWP/project2/01-yolo/autodistill/s.py", line 1, in <module>
    from autodistill_seggpt import SegGPT, FewShotOntology
  File "/home/smiv/anaconda3/envs/zwp_autodistill/lib/python3.9/site-packages/autodistill_seggpt/__init__.py", line 6, in <module>
    from .seggpt import SegGPT
  File "/home/smiv/anaconda3/envs/zwp_autodistill/lib/python3.9/site-packages/autodistill_seggpt/seggpt.py", line 63, in <module>
    from seggpt_engine import run_one_image
ModuleNotFoundError: No module named 'seggpt_engine'

**Comment by andrew-healey** [comment]
Thanks for reporting this! This bug is now fixed.

**Comment by alfheim1993** [comment]
I try it again, but the same as before
I create a new conda environment with python=3.11, and run pip install autodistill-seggpt,version is 0.1.6
I got the same import error ModuleNotFoundError: No module named 'seggpt_engine'
